### ISSUE TITLE
 unknown type name 'EventId' error

### ISSUE THREAD

**Issue by sumiteshpurohit** [CastXML/pygccxml#103]
When parsing several files from ns3 (e.g. src/mobility/model/random-waypoint-mobility-model.h), we are getting this error

error: unknown type name 'EventId'
  EventId m_event; //!< event ID of next scheduled event

Can you please help here?

**Comment by iMichka** [comment]
Hi. Could you provide that file, or at least a reduced example which is failing?

**Comment by sumiteshpurohit** [comment]
Below is the code i am running:

`from pygccxml import utils
from pygccxml import declarations
from pygccxml import parser

# Find the location of the xml generator (castxml or gccxml)
generator_path, generator_name = utils.find_xml_generator()

# Configure the xml generator
xml_generator_config = parser.xml_generator_configuration_t(
    xml_generator_path=generator_path,
    xml_generator=generator_name,
	cflags="-std=c++11", include_paths = ["build"])

# The c++ file we want to parse
filename = "src/mobility/model/random-waypoint-mobility-model.h"

# Parse the c++ file -- this is where the code is failing
decls = parser.parse([filename], xml_generator_config)

# Get access to the global namespace
global_namespace = declarations.get_global_namespace(decls)

# Get access to the 'ns' namespace
ns = global_namespace.namespace("ns")`

Attaching the image of error as well.
![image](https://user-images.githubusercontent.com/30154925/56941625-52502900-6b33-11e9-8b5d-3b3eb76ef4ca.png)

Please let me know if you need any other info.

**Comment by dermont123** [comment]
Try adding the header containing EventId first, e.g:
[ns3.zip](https://github.com/gccxml/pygccxml/files/3168539/ns3.zip)

**Comment by sumiteshpurohit** [comment]
> Try adding the header containing EventId first, e.g:
> [ns3.zip](https://github.com/gccxml/pygccxml/files/3168539/ns3.zip)

This works, thank you very much.

**Comment by iMichka** [comment]
Looks like this has been solved as the header needed to be included first.
