### ISSUE TITLE
When installing pygccxml through pip, declarations.dependencies is not installed

### ISSUE THREAD

**Issue by casey-tran** [CastXML/pygccxml#104]
Just noticed that when I installed pygccxml through pip, dependencies.py was not in the declarations directory. I tried creating a dependencies.py file with the source code off of Git, but my Python script is still having an AttributeError when I try to call the function dependencies.get_dependencies_from_decl(decls). I also created the dependencies.pyc file inside of the pycache folder inside of declarations as well.

**Comment by iMichka** [comment]
This is expected. The version provided by pip is version 1.9.1 which did not contain that file. I tested the package build with the latests develop branch and the file will be provided by release 2.0.
