### ISSUE TITLE
Add support for C++20 & 2b

### ISSUE THREAD

**Issue by LucHermitte** [CastXML/pygccxml#148]
In order to support C++20, `cxx_standard::__STD_CXX` dictionary in `utils/utils.py`  should be fixed to contain:

```python
...
        '-std=c++2a': 202002,
        '-std=gnu++2a': 202002,
        '-std=c++20': 202002,
        '-std=gnu++20': 202002,
        '-std=c++2b': float('inf'),
        '-std=gnu++2b': float('inf'),
```

But I'm not sure we should limit the list of valid values as we kind of know we have a new version every 3 years, and at most 3 (draft) versions per decade.

**Comment by iMichka** [comment]
I made the fix for the next release. Sadly I don't see a different solution right now. Better than nothing I guess.
