### ISSUE TITLE
Publishing pygccxml as Source Distribution on PyPi

### ISSUE THREAD

**Issue by Akira25** [CastXML/pygccxml#154]
For a GNURadio-Project, we decided to settle on a conda environment, to keep it fairly simple for our multi-platform-team.

While most things work really well, we are missing the pygccxml-package in the conda feeds, which are needed for generating some files when having a OOT-Module.

For generating a Conda-Package from the PyPi package, there is already a very simple workflow described in the [conda-wiki](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html).

Unfortunately, the conda stuff can not handle wheel-files, but relies on sdist instead. It would be marvelous, if you could publish pygccxml with an sdist file on pypi to.

**Comment by iMichka** [comment]
I made a new 2.3.0 release with a source distribution on pypi: https://pypi.org/project/pygccxml/2.3.0/

I will have a look how to do the whole distribution/release process using github actions to make sure we got this released correctly in the future.

Does this look good to you?

**Comment by iMichka** [comment]
Closing; this is now part of the release process that I have documented, and automatically done since we are using a pyproject.toml file for the build of the project.

**Comment by iMichka** [comment]
Done with https://github.com/CastXML/pygccxml/pull/258, wheels are now built on CI and have a build attestation on pypi
