### ISSUE TITLE
pygccxml error

### ISSUE THREAD

**Issue by senthilkuma** [CastXML/pygccxml#17]
Hello,
i was trying to scan python API that time i got these type of error 
so anyone help me to solve this error?

ubuntu@mn:~/ns-allinone-3.18.2/ns-3.18.1$ sudo ./waf --apiscan=netanim
sudo: unable to resolve host mn
Waf: Entering directory `/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build'
Modules to scan:  ['netanim']
api-scan-gcc_ILP32
INFO Parsing source file "/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h" ...
INFO gccxml cmd: /usr/bin/gccxml  --gccxml-cxxflags "-m32 -DPYTHON_SCAN"   -I"." -I"/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build"   "/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h" -fxml="/tmp/tmp01L_WN.xml"
Traceback (most recent call last):
  File "/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/bindings/python/ns3modulescan-modular.py", line 280, in <module>
    ns3_module_scan(sys.argv[1], sys.argv[2], eval(sys.argv[3]), sys.argv[4], sys.argv[5])
  File "/home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/bindings/python/ns3modulescan-modular.py", line 260, in ns3_module_scan
    gccxml_options=gccxml_options)
  File "/home/ubuntu/ns-allinone-3.18.2/pybindgen-0.16.0.834/pybindgen/gccxmlparser.py", line 683, in parse_init
    self.declarations = parser.parse(header_files, self.gccxml_config)
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/__init__.py", line 50, in parse
    answer = parser.read_files(files, compilation_mode)
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/project_reader.py", line 225, in read_files
    return self.__parse_file_by_file(files)
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/project_reader.py", line 250, in __parse_file_by_file
    decls = reader.read_file( header )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/source_reader.py", line 197, in read_file
    return self.read_gccxml_file( source_file )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/source_reader.py", line 224, in read_gccxml_file
    raise error
pygccxml.parser.source_reader.gccxml_runtime_error_t: Error occured while running GCC-XML: gccxml_cc1plus: error: gccxml_builtins.h: No such file or directory
In file included from /usr/include/c++/4.8/vector:60,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/stl_algobase.h: In function '_OI std::__copy_move_a(_II, _II, _OI)':
/usr/include/c++/4.8/bits/stl_algobase.h:384: error: expected primary-expression before ')' token
/usr/include/c++/4.8/bits/stl_algobase.h:384: error: there are no arguments to '__is_trivial' that depend on a template parameter, so a declaration of '__is_trivial' must be available
/usr/include/c++/4.8/bits/stl_algobase.h:384: error: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/include/c++/4.8/bits/stl_algobase.h:389: error: '__simple' cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_algobase.h:390: error: template argument 2 is invalid
/usr/include/c++/4.8/bits/stl_algobase.h: In function '_BI2 std::__copy_move_backward_a(_BI1, _BI1, _BI2)':
/usr/include/c++/4.8/bits/stl_algobase.h:579: error: expected primary-expression before ')' token
/usr/include/c++/4.8/bits/stl_algobase.h:579: error: there are no arguments to '__is_trivial' that depend on a template parameter, so a declaration of '__is_trivial' must be available
/usr/include/c++/4.8/bits/stl_algobase.h:584: error: '__simple' cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_algobase.h:585: error: template argument 2 is invalid
/usr/include/c++/4.8/bits/stl_algobase.h: In function 'typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp&)':
/usr/include/c++/4.8/bits/stl_algobase.h:737: error: expected`;' before '__niter'
/usr/include/c++/4.8/bits/stl_algobase.h:738: error: '__niter' was not declared in this scope
/usr/include/c++/4.8/bits/stl_algobase.h: In function 'typename __gnu_cxx::__enable_ifstd::__is_scalar<_Tp::__value, _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp&)':
/usr/include/c++/4.8/bits/stl_algobase.h:749: error: expected `;' before '__niter'
/usr/include/c++/4.8/bits/stl_algobase.h:750: error: '__niter' was not declared in this scope
In file included from /usr/include/c++/4.8/vector:61,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/allocator.h: At global scope:
/usr/include/c++/4.8/bits/allocator.h:159: error: expected primary-expression before ')' token
/usr/include/c++/4.8/bits/allocator.h:159: error: there are no arguments to '__is_empty' that depend on a template parameter, so a declaration of '__is_empty' must be available
/usr/include/c++/4.8/bits/allocator.h:176: error: expected primary-expression before ')' token
/usr/include/c++/4.8/bits/allocator.h:176: error: there are no arguments to '__is_empty' that depend on a template parameter, so a declaration of '__is_empty' must be available
In file included from /usr/include/c++/4.8/bits/stl_construct.h:61,
                 from /usr/include/c++/4.8/vector:62,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/ext/alloc_traits.h: In static member function 'static void __gnu_cxx::__alloc_traits<_Alloc>::_S_on_swap(_Alloc&, _Alloc&)':
/usr/include/c++/4.8/ext/alloc_traits.h:230: error: there are no arguments to '__is_empty' that depend on a template parameter, so a declaration of '__is_empty' must be available
/usr/include/c++/4.8/ext/alloc_traits.h:230: error: '__is_empty' was not declared in this scope
/usr/include/c++/4.8/ext/alloc_traits.h:230: error: template argument 2 is invalid
/usr/include/c++/4.8/ext/alloc_traits.h:230: error: invalid type in declaration before '(' token
In file included from /usr/include/c++/4.8/vector:62,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/stl_construct.h: In function 'void std::_Destroy(_ForwardIterator, _ForwardIterator)':
/usr/include/c++/4.8/bits/stl_construct.h:126: error: a function call cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_construct.h:126: error: template argument 1 is invalid
/usr/include/c++/4.8/bits/stl_construct.h:127: error: invalid type in declaration before '(' token
/usr/include/c++/4.8/bits/stl_construct.h:127: error: invalid use of qualified-name '::__destroy'
In file included from /usr/include/c++/4.8/vector:63,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/stl_uninitialized.h: In function '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator)':
/usr/include/c++/4.8/bits/stl_uninitialized.h:115: error: a function call cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_uninitialized.h:116: error: a function call cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_uninitialized.h:116: error: template argument 1 is invalid
/usr/include/c++/4.8/bits/stl_uninitialized.h: In function 'void std::uninitialized_fill(_ForwardIterator, _ForwardIterator, const _Tp&)':
/usr/include/c++/4.8/bits/stl_uninitialized.h:170: error: a function call cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_uninitialized.h:170: error: template argument 1 is invalid
/usr/include/c++/4.8/bits/stl_uninitialized.h:171: error: invalid type in declaration before '(' token
/usr/include/c++/4.8/bits/stl_uninitialized.h:171: error: invalid use of qualified-name '::__uninit_fill'
/usr/include/c++/4.8/bits/stl_uninitialized.h: In function 'void std::uninitialized_fill_n(_ForwardIterator, _Size, const _Tp&)':
/usr/include/c++/4.8/bits/stl_uninitialized.h:223: error: a function call cannot appear in a constant-expression
/usr/include/c++/4.8/bits/stl_uninitialized.h:223: error: template argument 1 is invalid
/usr/include/c++/4.8/bits/stl_uninitialized.h:224: error: invalid type in declaration before '(' token
/usr/include/c++/4.8/bits/stl_uninitialized.h:224: error: invalid use of qualified-name '::__uninit_fill_n'
In file included from /usr/include/c++/4.8/vector:65,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/stl_bvector.h: In member function 'void std::vector<bool, _Alloc>::swap(std::vector<bool, _Alloc>&)':
/usr/include/c++/4.8/bits/stl_bvector.h:844: error: there are no arguments to '__is_empty' that depend on a template parameter, so a declaration of '__is_empty' must be available
/usr/include/c++/4.8/bits/stl_bvector.h:844: error: '__is_empty' was not declared in this scope
/usr/include/c++/4.8/bits/stl_bvector.h:844: error: template argument 2 is invalid
/usr/include/c++/4.8/bits/stl_bvector.h:845: error: invalid type in declaration before '(' token
In file included from /usr/include/c++/4.8/string:40,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/object.h:25,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/node.h:26,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/animation-interface-helper.h:24,
                 from /home/ubuntu/ns-allinone-3.18.2/ns-3.18.1/build/ns3/netanim-module.h:10:
/usr/include/c++/4.8/bits/char_traits.h: In static member function 'static const char\* std::char_traits<char>::find(const char*, std::size_t, const char&)':

**Comment by tomastomcik** [comment]
Hi, can someone help me? I tried to run the gcc_xml program on Linux, I followed the instructions until I got to the point where I was told in command line that the number of arguments is too big, I don't think it's true because I have a 64 bit version. If I enter a blank argument into FLAGS it does not work, so I chose only the last argument from reading with the --print command, then I ran an example compilation file and my system dropped. Problem wasnt processor but memory, always asdcending . So I tried it on windows where I was told that the specified parameter is not valid, but I do not know which parameter.
Parameters are the following:
 Configuration settings:  GCCXML_CONFIG = ".......... l / Support / gccxml_config"
  GCCXML_COMPILER = "C: / Program Files (x86) / Microsoft Visual Studio 9.0 / VC / bin / cl.exe"
  GCCXML_CXXFLAGS = "/ DWIN32 / D_WINDOWS / W3 / GR / EHsc"
  GCCXML_EXECUTABLE = ""
  GCCXML_CPP = ""
  GCCXML_FLAGS = ""
  GCCXML_USER_FLAGS = ""
  GCCXML_ROOT = "................... / Support"
  GCCXML_ROOT_SRC = "....................... / gccxml-master / GCC_XML / Support"

can anyone advise me how do I set it up? For an early reply, thank you.
