### ISSUE TITLE
Drop support for gccxml

### ISSUE THREAD

**Issue by iMichka** [CastXML/pygccxml#81]
Release 2.0.0 will have one big change: I will remove the support for gccxml.
There are nowadays many package managers that have moved to CastXML, so this can be safely done. People which still want to use gccxml can pin version 1.9.x of pygccxml.

BTW, the name of the project will still stay like it is. I do not want to confuse people; and it is a tribute to neat tool that gccxml once was.

**Comment by EricCousineau-TRI** [comment]
Ah, just saw this after I filed #116. Will close that issue.

**Comment by EricCousineau-TRI** [comment]
Er, actually, how much do you think people would be confused?
You could just make the alias, put some deprecation notices in the alias, and you'd be good to go?
As far as a tribute goes, you could always reference it from your root-level README?

**Comment by iMichka** [comment]
Support has been dropped in version 2.0.0. Documentation updates are welcome if I missed some places.
